#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <cmath>

#define DEFAULT_HOSTNAME "localhost"
#define DEFAULT_PORT "58044"

#define UDP_TIMEOUT_SECONDS 4
#define UDP_RESEND_TRIES 3

#define SOCKET_BUFFER_LEN (256)
#define PACKET_ID_LEN (3)

#define PLAYER_ID_MAX_LEN (6)
#define PLAYER_ID_MAX ((uint32_t)pow(10, PLAYER_ID_MAX_LEN) - 1)

#define FILE_BUFFER_LEN (512)

#define HELP_MENU_COMMAND_COLUMN_WIDTH 20
#define HELP_MENU_DESCRIPTION_COLUMN_WIDTH 40
#define HELP_MENU_ALIAS_COLUMN_WIDTH 40

#endif
